service: yoga-serverless-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-1'}
  memorySize: 128
  logRetentionInDays: 1
  timeout: 15

functions:
  api:
    handler: dist/src/lambda.handler
    events:
      - httpApi:
          method: any
          path: /{proxy+}

plugins:
  - serverless-jetpack
  - serverless-offline
